import Head from "next/head";
import Header from "@/components/Header/Header";
import Hero from "@/components/Hero/Hero";
import About from "@/components/About/About";
import Plans from "@/components/Plans/Plans";
import BrandCarousel from "@/components/Brands/BrandCarousel";
import FAQ from "@/components/FAQ/FAQ";
import Services from "@/components/Services/Services";


function Home() {
    return (
        <>
            <Head>
                <title>Olena Moshko • SMM-specialist | content creator</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <Header/>
            <main>
                <Hero/>
                <BrandCarousel />
                <Services />
                <About/>
                <Plans />
                <FAQ />
            </main>
            <footer>

            </footer>
        </>
    );
}
export default Home;