import Head from "next/head";
import Header from "@/components/Header/Header";
import Hero from "@/components/Hero/Hero";
import About from "@/components/About/About";
import Plans from "@/components/Plans/Plans";
import BrandCarousel from "@/components/Brands/BrandCarousel";
import FAQ from "@/components/FAQ/FAQ";
import Services from "@/components/Services/Services";
import Contacts from "@/components/Contacts/Contacts";
import {useState} from "react";


function Home() {
    const [selectedPlan, setSelectedPlan] = useState(null); // Состояние для выбранного плана

    const handlePlanClick = (plan) => {
        setSelectedPlan(plan);
        console.log("Selected Plan:", plan);
    };

    return (
        <>
            <Head>
                <title>Olena Moshko • SMM-specialist | content creator</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <Header/>
            <main>
                <Hero/>
                <BrandCarousel/>
                <Services/>
                <About/>
                <Plans onPlanClick={handlePlanClick}/>
                <FAQ/>
                <Contacts plan={selectedPlan}/>
            </main>
            <footer>

            </footer>
        </>
    );
}

export default Home;